# Generated by Django 4.0.1 on 2022-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('agent', models.CharField(max_length=30, null=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
